apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - proxy.namespace.yaml
  - proxy.service.yaml
  - proxy.web.endpoint-slice.yaml
  - proxy.postgres.endpoint-slice.yaml
  - proxy.mail.endpoint-slice.yaml
